language: scala

scala:
- 2.11.1
jdk:
- openjdk7

env:
  - ACTIVATOR_VERSION=1.2.12
before_script:
  - wget http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
  - unzip -q typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
before_install:
  - unset SBT_OPTS JVM_OPTS
script:
  - travis_retry activator-${ACTIVATOR_VERSION}-minimal/activator update 
  - activator-${ACTIVATOR_VERSION}-minimal/activator test
